name: rustfmt

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  rustfmt:
    name: Rustfmt Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Rustfmt check
        run: cargo fmt -- --check -v
